### ISSUE TITLE
how to  select a maximum read-length

### ISSUE THREAD

**Issue by zhoudreames** [snurk/sg_sandbox#1]
![readlengths-obt](https://user-images.githubusercontent.com/54714639/143794017-01a32559-53fa-4d38-8fae-e2326419dd74.png)
this my distribution of read length,how to set the  maximum read-length ？ thanks~

**Comment by snurk** [comment]
I would suggest using 19 or 20 thousand here

**Comment by zhoudreames** [comment]
thanks~
